spring:
  datasource:
    driver-class-name: org.h2.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:test
#    url: jdbc:mysql://localhost:3306/gghqfw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1830000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
#    database: mysql
  h2:
    console:
      path: /h2-console
      enabled: true
# spring.h2.console.settings.web-allow-others=true //设置为true，h2 web consloe就可以在远程访问了。否则只能在本机访问。
# spring.h2.console.enabled=true                   //设置为true，程序开启时就会启动h2 web console(默认是false) 访问URL是 http://localhost:8080/h2-console
  application:
    name: baoan

logging:
  level: debug

